// <auto-generated />
using System;
using GymTrackerApi.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackerApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421092119_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GymTrackerApi.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("applicationuser");
                });

            modelBuilder.Entity("GymTrackerApi.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "A basic upper-body exercise targeting chest, shoulders, and triceps.",
                            Difficulty = 0,
                            LongDescription = "Push-ups are a classic exercise to build upper-body strength. They primarily target the chest, shoulders, and triceps, and also engage the core muscles. To perform a push-up, start in a plank position, keep your body straight, and lower yourself until your chest almost touches the floor. Then push back up.",
                            Name = "Push-up",
                            VideoUrl = "https://www.youtube.com/watch?v=Eh00_rniF8E&t=0s"
                        },
                        new
                        {
                            Id = 2,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Strengthens the core and stabilizes the spine.",
                            Difficulty = 1,
                            LongDescription = "Plank is lorem ipsum",
                            Name = "Plank",
                            VideoUrl = "https://www.youtube.com/watch?v=u6ZelKyUM6g"
                        },
                        new
                        {
                            Id = 3,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Engages lower body muscles, focusing on quads and glutes.",
                            Difficulty = 2,
                            LongDescription = "",
                            Name = "Squat",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Builds upper-body strength, mainly in the back and biceps.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Pull-up",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Targets triceps, chest, and shoulders.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Dips",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Focuses on core strength and lower abdominal muscles.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Leg Raises",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 7,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "A dynamic core and cardio exercise mimicking climbing motion.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Mountain Climbers",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 8,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "An advanced core isometric exercise.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "L-Sit",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 9,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Builds shoulder and core strength with balance training.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Handstand",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 10,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Static exercise engaging the quads and core.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Wall Sit",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 11,
                            BaseImage = "pullup.png",
                            Category = "Bodyweight Exercises",
                            Description = "Strengthens lower back and core while mimicking flight.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Superman Hold",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 12,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Develops chest, shoulders, and triceps with heavy resistance.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Bench Press",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 13,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "A compound exercise targeting back, legs, and glutes.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Deadlift",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 14,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Builds leg and core strength with loaded resistance.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Barbell Squat",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 15,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Strengthens shoulders and upper arms.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Shoulder Press",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 16,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Targets back muscles, mimicking pull-up motion.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Cable Pulldown",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 17,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Isolates and builds the biceps.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Bicep Curl",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 18,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Isolates the triceps using a cable machine.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Tricep Pushdown",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 19,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Targets quads, hamstrings, and glutes.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Leg Press",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 20,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Focuses on the upper chest and shoulders.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Incline Dumbbell Press",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 21,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Strengthens the back and improves posture.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Lat Pulldown",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 22,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Enhances shoulder stability and targets rear delts.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Face Pull",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 23,
                            BaseImage = "dumbbell.png",
                            Category = "Weight Training Exercises",
                            Description = "Develops glutes with emphasis on hip extension.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Hip Thrust",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 24,
                            BaseImage = "running.png",
                            Category = "Aerobic Exercises",
                            Description = "A full-body exercise improving cardio and strength.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Burpee",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 25,
                            BaseImage = "running.png",
                            Category = "Aerobic Exercises",
                            Description = "A dynamic cardio exercise.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Jumping Jacks",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = 26,
                            BaseImage = "running.png",
                            Category = "Aerobic Exercises",
                            Description = "Improves cardio and core strength.",
                            Difficulty = 0,
                            LongDescription = "",
                            Name = "Mountain Climbers",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("GymTrackerApi.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("GymTrackerApi.Models.TrainingExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExercises");
                });

            modelBuilder.Entity("GymTrackerApi.Models.Training", b =>
                {
                    b.HasOne("GymTrackerApi.Models.ApplicationUser", null)
                        .WithMany("Trainings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrackerApi.Models.TrainingExercise", b =>
                {
                    b.HasOne("GymTrackerApi.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerApi.Models.Training", "Training")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GymTrackerApi.Models.ApplicationUser", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("GymTrackerApi.Models.Training", b =>
                {
                    b.Navigation("TrainingExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
